"""Styled Excel report export (Part 6.4): header row styling, borders, number
formats, frozen header row, sized columns, a SUM() formula for the totals
row, and a summary sheet carrying the company name/contacts, KPIs and
report metadata. Everything is static (backend/branding.py)."""
from io import BytesIO

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

import branding

LIGHT = "EAF1F8"

THIN = Side(style="thin", color="BFBFBF")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)
MONEY_FORMAT = "#,##0.00"


def primary_hex():
    return branding.PRIMARY_COLOR.lstrip("#")


def company_name():
    return branding.COMPANY_NAME


def company_contacts():
    parts = [p for p in (branding.COMPANY_ADDRESS, branding.COMPANY_PHONE, branding.COMPANY_EMAIL) if p]
    return "  |  ".join(parts)


def excel_report(title, period, generated_by, kpis, columns, rows, numeric_cols=None, totals_row=None):
    """columns: header labels. rows: list of lists of raw values (numbers stay
    numbers, so Excel can sum them). numeric_cols: 0-based indexes formatted
    as money. totals_row: optional list; numeric cells get a SUM formula."""
    numeric_cols = set(numeric_cols or [])
    primary = primary_hex()
    header_fill = PatternFill("solid", fgColor=primary)
    header_font = Font(color="FFFFFF", bold=True)
    totals_fill = PatternFill("solid", fgColor=LIGHT)
    totals_font = Font(bold=True)
    workbook = Workbook()

    summary = workbook.active
    summary.title = "Summary"
    summary["A1"] = company_name()
    summary["A1"].font = Font(bold=True, size=16, color=primary)
    contacts = company_contacts()
    row_cursor = 2
    if contacts:
        summary[f"A{row_cursor}"] = contacts
        summary[f"A{row_cursor}"].font = Font(size=9, italic=True)
        row_cursor += 1
    row_cursor += 1
    summary[f"A{row_cursor}"] = title
    summary[f"A{row_cursor}"].font = Font(bold=True, size=14, color=primary)
    row_cursor += 1
    summary[f"A{row_cursor}"] = f"Period: {period}"
    row_cursor += 1
    summary[f"A{row_cursor}"] = f"Generated by: {generated_by}"
    row_cursor += 2
    for label, value in kpis or []:
        summary.cell(row=row_cursor, column=1, value=label).font = Font(bold=True)
        summary.cell(row=row_cursor, column=2, value=value)
        row_cursor += 1
    summary.column_dimensions["A"].width = 32
    summary.column_dimensions["B"].width = 24

    sheet = workbook.create_sheet(title[:31] or "Data")
    sheet.append(columns)
    for col_index in range(1, len(columns) + 1):
        cell = sheet.cell(row=1, column=col_index)
        cell.fill = header_fill
        cell.font = header_font
        cell.border = BORDER
        cell.alignment = Alignment(horizontal="center")

    for row in rows:
        sheet.append(row)

    data_row_count = len(rows)
    for r in range(2, 2 + data_row_count):
        for c in range(1, len(columns) + 1):
            cell = sheet.cell(row=r, column=c)
            cell.border = BORDER
            if (c - 1) in numeric_cols:
                cell.number_format = MONEY_FORMAT
                cell.alignment = Alignment(horizontal="right")

    if totals_row is not None:
        total_r = 2 + data_row_count
        for c, value in enumerate(totals_row, start=1):
            cell = sheet.cell(row=total_r, column=c)
            if (c - 1) in numeric_cols and data_row_count:
                col_letter = get_column_letter(c)
                cell.value = f"=SUM({col_letter}2:{col_letter}{total_r - 1})"
                cell.number_format = MONEY_FORMAT
                cell.alignment = Alignment(horizontal="right")
            else:
                cell.value = value
            cell.font = totals_font
            cell.fill = totals_fill
            cell.border = BORDER

    sheet.freeze_panes = "A2"
    for c, header in enumerate(columns, start=1):
        width = max(12, len(str(header)) + 4)
        sheet.column_dimensions[get_column_letter(c)].width = width

    stream = BytesIO()
    workbook.save(stream)
    stream.seek(0)
    return stream
