import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import AppShell from "../components/AppShell";
import { Button, Card, DataTable, Field, Input, Notice, PageHeader, money } from "../components/lms-ui";
import useResource from "../hooks/useResource.js";
import { assets, errorMessage } from "../lib/api";

export const Route = createFileRoute("/assets")({ component: AssetsPage });
const EMPTY = { name: "", type: "", value: "", date_acquired: "", notes: "" };
function AssetsPage() { const list = useResource(() => assets.list(), []); const [form, setForm] = useState<any>(EMPTY); const [editing, setEditing] = useState<number | null>(null); const [failure, setFailure] = useState(""); const [message, setMessage] = useState("");
  async function save(e: React.FormEvent) { e.preventDefault(); setFailure(""); try { const body = { ...form, value: Number(form.value) }; if (editing) await assets.update(editing, body); else await assets.create(body); setForm(EMPTY); setEditing(null); setMessage(editing ? "Asset updated." : "Asset created."); list.reload(); } catch (error) { setFailure(errorMessage(error)); } }
  async function remove(id: number) { try { await assets.remove(id); list.reload(); } catch (error) { setFailure(errorMessage(error)); } }
  return <AppShell><PageHeader title="Assets" description="Track branch assets and their current value." /><Notice tone="success">{message}</Notice><Notice tone="danger">{failure || list.error}</Notice><div className="grid gap-4 xl:grid-cols-[1.7fr_1fr]"><Card title="Asset register"><DataTable rows={list.data || []} empty={list.loading ? "Loading..." : "No assets."} columns={[{ key: "name", label: "Name" }, { key: "type", label: "Type" }, { key: "value", label: "Value", render: (r: any) => money(r.value) }, { key: "date_acquired", label: "Acquired" }, { key: "actions", label: "", render: (r: any) => <div className="flex gap-2"><Button variant="outline" onClick={() => { setEditing(r.id); setForm({ name: r.name, type: r.type, value: r.value, date_acquired: r.date_acquired, notes: r.notes || "" }); }}>Edit</Button><Button variant="outline" onClick={() => remove(r.id)}>Delete</Button></div> }]} /></Card><Card title={editing ? "Edit asset" : "Add asset"}><form className="space-y-3" onSubmit={save}><Field label="Name"><Input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field><Field label="Type"><Input required value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })} /></Field><Field label="Value"><Input type="number" step="0.01" required value={form.value} onChange={(e) => setForm({ ...form, value: e.target.value })} /></Field><Field label="Date acquired"><Input type="date" required value={form.date_acquired} onChange={(e) => setForm({ ...form, date_acquired: e.target.value })} /></Field><Field label="Notes"><Input value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></Field><Button type="submit" className="w-full">{editing ? "Update asset" : "Save asset"}</Button></form></Card></div></AppShell>;
}
