import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import AppShell from "../components/AppShell";
import { Button, Card, DataTable, Field, Input, Notice, PageHeader, Select, StatusBadge } from "../components/lms-ui";
import useResource from "../hooks/useResource.js";
import { employees, errorMessage, getUser, leaveRequests } from "../lib/api";

export const Route = createFileRoute("/leave-requests")({ component: LeaveRequestsPage });
function LeaveRequestsPage() { const list = useResource(() => leaveRequests.list(), []); const staff = useResource(() => employees.list(), []); const user = getUser(); const [form, setForm] = useState<any>({ employee_id: "", leave_type: "Annual", start_date: "", end_date: "", reason: "" }); const [failure, setFailure] = useState(""); const [message, setMessage] = useState("");
  async function create(e: React.FormEvent) { e.preventDefault(); try { await leaveRequests.create({ ...form, employee_id: Number(form.employee_id) }); setMessage("Leave request submitted."); list.reload(); } catch (error) { setFailure(errorMessage(error)); } }
  async function decide(id: number, action: "approve" | "reject") { try { await leaveRequests[action](id, action === "reject" ? "Rejected by checker" : undefined as any); list.reload(); } catch (error) { setFailure(errorMessage(error)); } }
  return <AppShell><PageHeader title="Leave requests" description="Submit and review staff leave requests." /><Notice tone="success">{message}</Notice><Notice tone="danger">{failure || list.error}</Notice><div className="grid gap-4 xl:grid-cols-[1.7fr_1fr]"><Card title="Requests"><DataTable rows={list.data || []} empty={list.loading ? "Loading..." : "No leave requests."} columns={[{ key: "id", label: "Ref" }, { key: "employee_id", label: "Employee" }, { key: "leave_type", label: "Type" }, { key: "start_date", label: "From" }, { key: "end_date", label: "To" }, { key: "status", label: "Status", render: (r: any) => <StatusBadge status={r.status} /> }, { key: "actions", label: "", render: (r: any) => <div className="flex gap-2"><Button disabled={r.created_by === user?.id} onClick={() => decide(r.id, "approve")}>Approve</Button><Button variant="outline" disabled={r.created_by === user?.id} onClick={() => decide(r.id, "reject")}>Reject</Button></div> }]} /></Card><Card title="Request leave"><form className="space-y-3" onSubmit={create}><Field label="Employee"><Select required value={form.employee_id} onChange={(e) => setForm({ ...form, employee_id: e.target.value })}><option value="">Select employee</option>{(staff.data || []).map((row: any) => <option value={row.id} key={row.id}>{row.name}</option>)}</Select></Field><Field label="Leave type"><Input required value={form.leave_type} onChange={(e) => setForm({ ...form, leave_type: e.target.value })} /></Field><Field label="Start date"><Input type="date" required value={form.start_date} onChange={(e) => setForm({ ...form, start_date: e.target.value })} /></Field><Field label="End date"><Input type="date" required value={form.end_date} onChange={(e) => setForm({ ...form, end_date: e.target.value })} /></Field><Field label="Reason"><Input value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })} /></Field><Button type="submit" className="w-full">Submit request</Button></form></Card></div></AppShell>;
}
