import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import AppShell from "../components/AppShell";
import { Button, Card, DataTable, Notice, PageHeader, Select } from "../components/lms-ui";
import { errorMessage, reports } from "../lib/api";

export const Route = createFileRoute("/reports")({ component: ReportsPage });
const REPORTS: Record<string, { label: string; path: string; key: string }> = { "portfolio-at-risk": { label: "Portfolio at risk", path: "portfolio-at-risk", key: "buckets" }, collections: { label: "Collections", path: "collections", key: "collections" }, "borrower-statement": { label: "Borrower statement", path: "borrower-statement/1", key: "statement" }, "capital-flow": { label: "Capital flow", path: "capital-flow", key: "flow" }, "loan-officer-performance": { label: "Officer performance", path: "loan-officer-performance", key: "officers" } };
function ReportsPage() { const [selected, setSelected] = useState("portfolio-at-risk"); const [data, setData] = useState<any[]>([]); const [failure, setFailure] = useState(""); const report = REPORTS[selected];
  async function load() { try { const payload = await reports.get(report.path, selected === "collections" ? { period: "monthly" } : {}); setData(payload[report.key] || []); } catch (error) { setFailure(errorMessage(error)); } }
  async function download(format: "pdf" | "excel") { try { const blob = await reports.download(report.path, format, selected === "collections" ? { period: "monthly" } : {}); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `${selected}.${format === "pdf" ? "pdf" : "xlsx"}`; link.click(); URL.revokeObjectURL(url); } catch (error) { setFailure(errorMessage(error)); } }
  return <AppShell><PageHeader title="Reports" description="Review and export operational reports." /><Notice tone="danger">{failure}</Notice><Card><div className="mb-4 flex flex-wrap gap-2"><Select value={selected} onChange={(e) => { setSelected(e.target.value); setData([]); }}><option value="portfolio-at-risk">Portfolio at risk</option><option value="collections">Collections</option><option value="borrower-statement">Borrower statement</option><option value="capital-flow">Capital flow</option><option value="loan-officer-performance">Loan officer performance</option></Select><Button onClick={load}>Load report</Button><Button variant="outline" onClick={() => download("pdf")}>Download PDF</Button><Button variant="outline" onClick={() => download("excel")}>Download Excel</Button></div><DataTable rows={data} empty="Load a report to view results." columns={data.length ? Object.keys(data[0]).map((key) => ({ key, label: key.replace(/_/g, " ") })) : [{ key: "empty", label: "Report data" }]} /></Card></AppShell>;
}
