/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as CapitalRouteImport } from './routes/capital'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DeductionTypesRouteImport } from './routes/deduction-types'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as LeaveRequestsRouteImport } from './routes/leave-requests'
import { Route as LoanCalculatorRouteImport } from './routes/loan-calculator'
import { Route as LoanProductsRouteImport } from './routes/loan-products'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as PenaltiesRouteImport } from './routes/penalties'
import { Route as RepaymentsRouteImport } from './routes/repayments'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as UsersRouteImport } from './routes/users'
import { Route as BorrowersIndexRouteImport } from './routes/borrowers.index'
import { Route as BorrowersIdRouteImport } from './routes/borrowers.$id'
import { Route as LoansIndexRouteImport } from './routes/loans.index'
import { Route as LoansIdRouteImport } from './routes/loans.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const CapitalRoute = CapitalRouteImport.update({
  id: '/capital',
  path: '/capital',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeductionTypesRoute = DeductionTypesRouteImport.update({
  id: '/deduction-types',
  path: '/deduction-types',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRequestsRoute = LeaveRequestsRouteImport.update({
  id: '/leave-requests',
  path: '/leave-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanCalculatorRoute = LoanCalculatorRouteImport.update({
  id: '/loan-calculator',
  path: '/loan-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanProductsRoute = LoanProductsRouteImport.update({
  id: '/loan-products',
  path: '/loan-products',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PenaltiesRoute = PenaltiesRouteImport.update({
  id: '/penalties',
  path: '/penalties',
  getParentRoute: () => rootRouteImport,
} as any)
const RepaymentsRoute = RepaymentsRouteImport.update({
  id: '/repayments',
  path: '/repayments',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const BorrowersIndexRoute = BorrowersIndexRouteImport.update({
  id: '/borrowers/',
  path: '/borrowers/',
  getParentRoute: () => rootRouteImport,
} as any)
const BorrowersIdRoute = BorrowersIdRouteImport.update({
  id: '/borrowers/$id',
  path: '/borrowers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansIndexRoute = LoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansIdRoute = LoansIdRouteImport.update({
  id: '/loans/$id',
  path: '/loans/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/assets': typeof AssetsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/backup': typeof BackupRoute
  '/capital': typeof CapitalRoute
  '/dashboard': typeof DashboardRoute
  '/deduction-types': typeof DeductionTypesRoute
  '/employees': typeof EmployeesRoute
  '/expenses': typeof ExpensesRoute
  '/leave-requests': typeof LeaveRequestsRoute
  '/loan-calculator': typeof LoanCalculatorRoute
  '/loan-products': typeof LoanProductsRoute
  '/payroll': typeof PayrollRoute
  '/penalties': typeof PenaltiesRoute
  '/repayments': typeof RepaymentsRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRoute
  '/borrowers/$id': typeof BorrowersIdRoute
  '/loans/$id': typeof LoansIdRoute
  '/borrowers/': typeof BorrowersIndexRoute
  '/loans/': typeof LoansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/assets': typeof AssetsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/backup': typeof BackupRoute
  '/capital': typeof CapitalRoute
  '/dashboard': typeof DashboardRoute
  '/deduction-types': typeof DeductionTypesRoute
  '/employees': typeof EmployeesRoute
  '/expenses': typeof ExpensesRoute
  '/leave-requests': typeof LeaveRequestsRoute
  '/loan-calculator': typeof LoanCalculatorRoute
  '/loan-products': typeof LoanProductsRoute
  '/payroll': typeof PayrollRoute
  '/penalties': typeof PenaltiesRoute
  '/repayments': typeof RepaymentsRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRoute
  '/borrowers/$id': typeof BorrowersIdRoute
  '/loans/$id': typeof LoansIdRoute
  '/borrowers': typeof BorrowersIndexRoute
  '/loans': typeof LoansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/assets': typeof AssetsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/backup': typeof BackupRoute
  '/capital': typeof CapitalRoute
  '/dashboard': typeof DashboardRoute
  '/deduction-types': typeof DeductionTypesRoute
  '/employees': typeof EmployeesRoute
  '/expenses': typeof ExpensesRoute
  '/leave-requests': typeof LeaveRequestsRoute
  '/loan-calculator': typeof LoanCalculatorRoute
  '/loan-products': typeof LoanProductsRoute
  '/payroll': typeof PayrollRoute
  '/penalties': typeof PenaltiesRoute
  '/repayments': typeof RepaymentsRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRoute
  '/borrowers/$id': typeof BorrowersIdRoute
  '/loans/$id': typeof LoansIdRoute
  '/borrowers/': typeof BorrowersIndexRoute
  '/loans/': typeof LoansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/assets'
    | '/audit-logs'
    | '/backup'
    | '/capital'
    | '/dashboard'
    | '/deduction-types'
    | '/employees'
    | '/expenses'
    | '/leave-requests'
    | '/loan-calculator'
    | '/loan-products'
    | '/payroll'
    | '/penalties'
    | '/repayments'
    | '/reports'
    | '/users'
    | '/borrowers/$id'
    | '/loans/$id'
    | '/borrowers/'
    | '/loans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/assets'
    | '/audit-logs'
    | '/backup'
    | '/capital'
    | '/dashboard'
    | '/deduction-types'
    | '/employees'
    | '/expenses'
    | '/leave-requests'
    | '/loan-calculator'
    | '/loan-products'
    | '/payroll'
    | '/penalties'
    | '/repayments'
    | '/reports'
    | '/users'
    | '/borrowers/$id'
    | '/loans/$id'
    | '/borrowers'
    | '/loans'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/assets'
    | '/audit-logs'
    | '/backup'
    | '/capital'
    | '/dashboard'
    | '/deduction-types'
    | '/employees'
    | '/expenses'
    | '/leave-requests'
    | '/loan-calculator'
    | '/loan-products'
    | '/payroll'
    | '/penalties'
    | '/repayments'
    | '/reports'
    | '/users'
    | '/borrowers/$id'
    | '/loans/$id'
    | '/borrowers/'
    | '/loans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AssetsRoute: typeof AssetsRoute
  AuditLogsRoute: typeof AuditLogsRoute
  BackupRoute: typeof BackupRoute
  CapitalRoute: typeof CapitalRoute
  DashboardRoute: typeof DashboardRoute
  DeductionTypesRoute: typeof DeductionTypesRoute
  EmployeesRoute: typeof EmployeesRoute
  ExpensesRoute: typeof ExpensesRoute
  LeaveRequestsRoute: typeof LeaveRequestsRoute
  LoanCalculatorRoute: typeof LoanCalculatorRoute
  LoanProductsRoute: typeof LoanProductsRoute
  PayrollRoute: typeof PayrollRoute
  PenaltiesRoute: typeof PenaltiesRoute
  RepaymentsRoute: typeof RepaymentsRoute
  ReportsRoute: typeof ReportsRoute
  UsersRoute: typeof UsersRoute
  BorrowersIdRoute: typeof BorrowersIdRoute
  LoansIdRoute: typeof LoansIdRoute
  BorrowersIndexRoute: typeof BorrowersIndexRoute
  LoansIndexRoute: typeof LoansIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capital': {
      id: '/capital'
      path: '/capital'
      fullPath: '/capital'
      preLoaderRoute: typeof CapitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deduction-types': {
      id: '/deduction-types'
      path: '/deduction-types'
      fullPath: '/deduction-types'
      preLoaderRoute: typeof DeductionTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave-requests': {
      id: '/leave-requests'
      path: '/leave-requests'
      fullPath: '/leave-requests'
      preLoaderRoute: typeof LeaveRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-calculator': {
      id: '/loan-calculator'
      path: '/loan-calculator'
      fullPath: '/loan-calculator'
      preLoaderRoute: typeof LoanCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-products': {
      id: '/loan-products'
      path: '/loan-products'
      fullPath: '/loan-products'
      preLoaderRoute: typeof LoanProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penalties': {
      id: '/penalties'
      path: '/penalties'
      fullPath: '/penalties'
      preLoaderRoute: typeof PenaltiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repayments': {
      id: '/repayments'
      path: '/repayments'
      fullPath: '/repayments'
      preLoaderRoute: typeof RepaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borrowers/': {
      id: '/borrowers/'
      path: '/borrowers'
      fullPath: '/borrowers/'
      preLoaderRoute: typeof BorrowersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borrowers/$id': {
      id: '/borrowers/$id'
      path: '/borrowers/$id'
      fullPath: '/borrowers/$id'
      preLoaderRoute: typeof BorrowersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/': {
      id: '/loans/'
      path: '/loans'
      fullPath: '/loans/'
      preLoaderRoute: typeof LoansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/$id': {
      id: '/loans/$id'
      path: '/loans/$id'
      fullPath: '/loans/$id'
      preLoaderRoute: typeof LoansIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  AssetsRoute: AssetsRoute,
  AuditLogsRoute: AuditLogsRoute,
  BackupRoute: BackupRoute,
  CapitalRoute: CapitalRoute,
  DashboardRoute: DashboardRoute,
  DeductionTypesRoute: DeductionTypesRoute,
  EmployeesRoute: EmployeesRoute,
  ExpensesRoute: ExpensesRoute,
  LeaveRequestsRoute: LeaveRequestsRoute,
  LoanCalculatorRoute: LoanCalculatorRoute,
  LoanProductsRoute: LoanProductsRoute,
  PayrollRoute: PayrollRoute,
  PenaltiesRoute: PenaltiesRoute,
  RepaymentsRoute: RepaymentsRoute,
  ReportsRoute: ReportsRoute,
  UsersRoute: UsersRoute,
  BorrowersIdRoute: BorrowersIdRoute,
  LoansIdRoute: LoansIdRoute,
  BorrowersIndexRoute: BorrowersIndexRoute,
  LoansIndexRoute: LoansIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
